"""
This type stub file was generated by pyright.
"""

from . import particule


def fade_color(particle: particule.Particle, color: tuple[int, int, int], progress: float) -> tuple[int, int, int]:
    ...

def fade_alpha(particle: particule.Particle, alpha: int, progress: float) -> int:
    ...

def fade_alpha_exp(particle: particule.Particle, alpha: int, progress: float) -> int:
    ...

