"""
This type stub file was generated by pyright.
"""

from pygame.surface import Surface

class Shape:
    def __init__(self, alpha: int = ..., color: tuple[int, int, int] = ..., angle: float = ...) -> None:
        self.surface: Surface
        self.color: tuple[int, int, int]
        self.alpha: int
        self.angle: float
    
    def orig_alpha(self) -> int:
        ...
    
    def orig_angle(self) -> float:
        ...
    
    def orig_color(self) -> tuple[int, int, int]:
        ...
    
    def check_size_above_zero(self) -> bool:
        ...
    
    def get_progress(self) -> tuple[float, float]:
        ...
    
    def decrease(self, delta: float) -> None:
        ...
    
    def make_surface(self) -> Surface:
        ...
    
    def make_shape(self) -> None:
        ...
    


class BaseForm(Shape):
    def __init__(self, radius: float, color: tuple[int, int, int], alpha: int = ..., angle: float = ...) -> None:
        ...
    
    def orig_radius(self) -> float:
        ...
    
    def orig_color(self) -> tuple[int, int, int]:
        ...
    
    def check_size_above_zero(self) -> bool:
        ...
    
    def get_progress(self) -> tuple[float, float]:
        ...
    
    def decrease(self, delta: float) -> None:
        ...
    
    def make_surface(self) -> Surface:
        ...
    
    def make_shape(self) -> None:
        ...
    


class Circle(BaseForm):
    def __init__(self, radius: float, color: tuple[int, int, int], alpha: int = ..., angle: float = ...) -> None:
        ...
    
    def make_shape(self) -> None:
        ...
    


class Rect(BaseForm):
    def __init__(self, radius: float, color: tuple[int, int, int], alpha: int = ..., angle: float = ...) -> None:
        ...
    
    def make_shape(self) -> None:
        ...
    


